GET http://localhost:5281


###
GET http://localhost:5281/users
###
GET http://localhost:5281/users/1
###
POST http://localhost:5281/users
Content-Type: application/json

{
    "UserName": "Geniy",
    "Password": "Izi"
}
###
POST http://localhost:5281/auth/jwttoken/login
Content-Type: application/json

{
    "UserName": "Geniy",
    "Password": "Izi"
}

###
PUT http://localhost:5281/users/1
Content-Type: application/json

{
    "UserName": "Admin",
    "Password": "SuperSecretPassword"
}

###
DELETE http://localhost:5281/users/2
###
###
###

